# Generated by Django 3.0.3 on 2020-03-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pghotels',
            name='location',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
