# Generated by Django 3.0.3 on 2020-03-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_pghotels_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pghotels',
            name='desc',
        ),
    ]
